Add config file support in gcode pre-processing pipeline to fix "TypeError: main() missing 1 required positional argument: 'config' " Error when gcode is uploaded.